export const RANDOM_METHODS: string[] = [
  'RANDOM',
  'ASCENDING',
  'DESCENDING',
  'ASCENDING_ALMOST',
  'DESCENDING_ALMOST'
] as const;

export const VISUALIZER_DEFAULTS = {
  LANG: 'en',
  MAX_ELEMENT_COUNT_DIVISOR: 14,
  MAX_VALUE_OFFSET_MULTIPLIER: 0.45,
  SORT_DELAY: 50,
  SORT_STYLE: 'BAR',
  RANDOM_METHOD: 'RANDOM',
  ELEMENT_COUNT: 400,
  UNIQUE_COUNT: 400,
  MIN_VALUE: 5,
  MAX_VALUE: 600,
  AUDIO_GAIN: 6,
  AUDIO_GAIN_MULTIPLIER: 0.02,
  AUDIO_MS: 50,
  AUDIO_OSCILLATOR_TYPE: 'triangle', // "sine" < "triangle" < "square" < "sawtooth"
  AUDIO_OSCILLATOR_TIMEOUT: 0.001,
  SWAPLINE_OFFSET_X: 12,
  SWAPLINE_OFFSET_Y: 30,
  SWAPLINE_CURVE_PEAK: 100,
  SWIPE_THRESHOLD: 10
} as const;